"""baseline schema

Revision ID: 29823c6a0cd9
Revises:
Create Date: 2026-06-07 11:26:36.864862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '29823c6a0cd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('geocoding_cache',
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('query')
    )
    op.create_index(op.f('ix_geocoding_cache_query'), 'geocoding_cache', ['query'], unique=False)
    op.create_table('semantic_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('query_embedding', Vector(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('use_count', sa.Float(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('freshness_days', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_cache_category'), 'semantic_cache', ['category'], unique=False)
    op.create_index(op.f('ix_semantic_cache_created_at'), 'semantic_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_semantic_cache_destination'), 'semantic_cache', ['destination'], unique=False)
    op.create_index(op.f('ix_semantic_cache_query_text'), 'semantic_cache', ['query_text'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('default_budget', sa.String(), nullable=True),
    sa.Column('default_interests', sa.String(), nullable=True),
    sa.Column('num_travelers', sa.Integer(), nullable=True),
    sa.Column('age_range', sa.String(), nullable=True),
    sa.Column('trip_type', sa.String(), nullable=True),
    sa.Column('start_location', sa.String(), nullable=True),
    sa.Column('constraints', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('interests', sa.String(), nullable=True),
    sa.Column('itinerary_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_destination'), 'trips', ['destination'], unique=False)
    op.create_index(op.f('ix_trips_session_id'), 'trips', ['session_id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_session_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_semantic_cache_query_text'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_destination'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_created_at'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_category'), table_name='semantic_cache')
    op.drop_table('semantic_cache')
    op.drop_index(op.f('ix_geocoding_cache_query'), table_name='geocoding_cache')
    op.drop_table('geocoding_cache')
    # ### end Alembic commands ###
